CREATE DATABASE VITAGARDENN_1

USE VITAGARDENN_1

CREATE TABLE EMPLEADO
(
	ID_EMPLEADO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	SALARIO MONEY NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
)

CREATE TABLE ESPECIE
(
	ID_ESPECIE BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	ESTADO VARCHAR (50) NOT NULL
)

CREATE TABLE VENTA 
(
	ID_VENTA BIGINT PRIMARY KEY NOT NULL,
	VALOR MONEY NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA DATETIME NOT NULL,
	IVA MONEY NOT NULL,
	ID_EMPLEADO_FK_VENTA BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_VENTA FOREIGN KEY (ID_EMPLEADO_FK_VENTA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_CLIENTE_FK_VENTA BIGINT NOT NULL,
	CONSTRAINT ID_CLIENTE_FK_VENTA FOREIGN KEY (ID_CLIENTE_FK_VENTA) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE ENTRADA_COMPRA
(
	ID_ENTRADA_COMPRA BIGINT PRIMARY KEY NOT NULL,
	FECHA DATETIME NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	ID_COMPRA_FK_ENTRADA_COMPRA BIGINT NOT NULL,
	CONSTRAINT ID_COMPRA_FK_ENTRADA_COMPRA FOREIGN KEY (ID_COMPRA_FK_ENTRADA_COMPRA) REFERENCES COMPRA (ID_COMPRA),
	ID_EMPLEADO_FK_ENTRADA_COMPRA BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_ENTRADA_COMPRA FOREIGN KEY (ID_EMPLEADO_FK_ENTRADA_COMPRA) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE COMPRA
(
	ID_COMPRA BIGINT PRIMARY KEY NOT NULL,
	CANTIDAD INT NOT NULL,
	VALOR MONEY NOT NULL,
	ESTADO VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_COMPRA BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_COMPRA FOREIGN KEY (ID_EMPLEADO_FK_COMPRA) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_PROVEEDOR_FK_COMPRA BIGINT NOT NULL,
	CONSTRAINT ID_PROVEEDOR_FK_COMPRA FOREIGN KEY (ID_PROVEEDOR_FK_COMPRA) REFERENCES PROVEEDOR (ID_PROVEEDOR)
)

CREATE TABLE TELEFONO_EMPLEADO
(
	ID_TELEFONO BIGINT PRIMARY KEY NOT NULL,
	NUMERO INT NOT NULL,
	ID_EMPLEADO_FK_TELEFONO BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_TELEFONO FOREIGN KEY (ID_EMPLEADO_FK_TELEFONO) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE USUARIO
(
	NOMBRE VARCHAR(40) PRIMARY KEY NOT NULL,
	CONTRASEÑA INT NOT NULL,
	ID_EMPLEADO_FK_USUARIO BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_USUARIO FOREIGN KEY (ID_EMPLEADO_FK_USUARIO) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE CLIENTE 
(
	ID_CLIENTE BIGINT PRIMARY KEY NOT NULL,
	EMAIL VARCHAR (40) NOT NULL,
	NOMBRE VARCHAR (40) NOT NULL,
	ESTADO VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_CLIENTE BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_CLIENTE FOREIGN KEY (ID_EMPLEADO_FK_CLIENTE) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE TELEFONO_CLIENTE
(
	ID_TELEFONO BIGINT PRIMARY KEY NOT NULL,
	NUMERO INT NOT NULL,
	ID_CLIENTE_FK_TELEFONO BIGINT NOT NULL,
	CONSTRAINT ID_CLIENTE_FK_TELEFONO FOREIGN KEY (ID_CLIENTE_FK_TELEFONO) REFERENCES CLIENTE (ID_CLIENTE)
)

CREATE TABLE PROVEEDOR
(
	ID_PROVEEDOR BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	VALOR MONEY NOT NULL,
	CIUDAD VARCHAR(30) NOT NULL,
	DIRECCION VARCHAR(50) NULL,
	ESTADO VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_PROVEEDOR BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PROVEEDOR FOREIGN KEY (ID_EMPLEADO_FK_PROVEEDOR) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE TELEFONO_PROVEEDOR
(
	ID_TELEFONO BIGINT PRIMARY KEY NOT NULL,
	NUMERO INT NOT NULL,
	ID_PROVEEDOR_FK_TELEFONO BIGINT NOT NULL,
	CONSTRAINT ID_PROVEEDOR_FK_TELEFONO FOREIGN KEY (ID_PROVEEDOR_FK_TELEFONO) REFERENCES PROVEEDOR (ID_PROVEEDOR)
)

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	VALOR MONEY NOT NULL,
	CANTIDAD INT NOT NULL,
	ESTADO VARCHAR (50) NOT NULL,
	ID_EMPLEADO_FK_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PRODUCTO FOREIGN KEY (ID_EMPLEADO_FK_PRODUCTO) REFERENCES EMPLEADO (ID_EMPLEADO),
	ID_PROVEEDOR_FK_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PROVEEDOR_FK_PRODUCTO FOREIGN KEY (ID_PROVEEDOR_FK_PRODUCTO) REFERENCES PROVEEDOR (ID_PROVEEDOR)
)

CREATE TABLE TIPO_PRODUCTO
(
	ID_TIPO_PRODUCTO BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20),
	ESTADO VARCHAR (50),
	ID_PRODUCTO_FK_TIPO_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_TIPO_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_TIPO_PRODUCTO)REFERENCES PRODUCTO (ID_PRODUCTO)
)

CREATE TABLE MARCA
(
	ID_MARCA BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(30) NULL,
	ID_PRODUCTO_FK_MARCA BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_MARCA FOREIGN KEY (ID_PRODUCTO_FK_MARCA) REFERENCES PRODUCTO (ID_PRODUCTO)
)

CREATE TABLE VENTA_PRODUCTO
(
	OBSERVACIONES VARCHAR(100) NULL,
	CANTIDAD INT NOT NULL,
	VALOR MONEY NOT NULL,
	ID_PRODUCTO_FK_VENTA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_VENTA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_VENTA_FK_VENTA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_VENTA_FK_VENTA_PRODUCTO FOREIGN KEY (ID_VENTA_FK_VENTA_PRODUCTO) REFERENCES VENTA (ID_VENTA)
)

CREATE TABLE PLANTA
(
	ID_PLANTA BIGINT PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(60) NOT NULL,
	VALOR MONEY NOT NULL,
	CANTIDAD INT NOT NULL,
	ESTADO VARCHAR (50) NOT NULL,
	ID_ESPECIE_FK_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_ESPECIE_FK_PLANTA FOREIGN KEY (ID_ESPECIE_FK_PLANTA) REFERENCES ESPECIE (ID_ESPECIE),
	ID_EMPLEADO_FK_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_PLANTA FOREIGN KEY (ID_EMPLEADO_FK_PLANTA) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE VENTA_PLANTA
(
	OBSERVACIONES VARCHAR(100) NULL,
	CANTIDAD INT NOT NULL,
	SUBTOTAL MONEY NOT NULL,
	ID_PLANTA_FK_VENTA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_PLANTA_FK_VENTA_PLANTA FOREIGN KEY (ID_PLANTA_FK_VENTA_PLANTA) REFERENCES PLANTA (ID_PLANTA),
	ID_VENTA_FK_VENTA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_VENTA_FK_VENTA_PLANTA FOREIGN KEY (ID_VENTA_FK_VENTA_PLANTA) REFERENCES VENTA (ID_VENTA)
)

CREATE TABLE ENTRADA_PRODUCTO
(
	CANTIDAD INT NOT NULL,
	VALOR MONEY NOT NULL,
	ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_ENTRADA_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_ENTRADA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_ENTRADA_COMPRA_FK_VENTA_ENTRADA BIGINT NOT NULL,
	CONSTRAINT ID_ENTRADA_COMPRA_FK_ENTRADA_PRODUCTO FOREIGN KEY (ID_ENTRADA_COMPRA_FK_VENTA_ENTRADA) REFERENCES ENTRADA_COMPRA (ID_ENTRADA_COMPRA)
)

CREATE TABLE COMPRA_PRODUCTO
(
	FECHA DATETIME NOT NULL,
	HORA DATETIME NOT NULL,
	ID_PRODUCTO_FK_COMPRA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_COMPRA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_COMPRA_FK_COMPRA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_COMPRA_FK_COMPRA_PRODUCTO FOREIGN KEY (ID_COMPRA_FK_COMPRA_PRODUCTO) REFERENCES COMPRA (ID_COMPRA)
)

CREATE TABLE ENTRADA_PLANTA
(
	OBSERVACIONES VARCHAR(100) NOT NULL,
	CANTIDAD INT NOT NULL,
	ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA FOREIGN KEY (ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA) REFERENCES ENTRADA_COMPRA (ID_ENTRADA_COMPRA),
	ID_PLANTA_FK_ENTRADA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_PLANTA_FK_ENTRADA_PLANTA FOREIGN KEY (ID_PLANTA_FK_ENTRADA_PLANTA) REFERENCES PLANTA (ID_PLANTA)
)

CREATE TABLE SALIDA_INVENTARIO
(
	ID_SALIDA_INVENTARIO BIGINT PRIMARY KEY NOT NULL,
	FECHA DATETIME NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	ID_VENTA_FK_SALIDA_INVENTARIO BIGINT NOT NULL,
	CONSTRAINT ID_VENTA_FK_SALIDA_INVENTARIO FOREIGN KEY (ID_VENTA_FK_SALIDA_INVENTARIO) REFERENCES VENTA (ID_VENTA),
	ID_EMPLEADO_FK_SALIDA_INVENTARIO BIGINT NOT NULL,
	CONSTRAINT ID_EMPLEADO_FK_SALIDA_INVENTARIO FOREIGN KEY (ID_EMPLEADO_FK_SALIDA_INVENTARIO) REFERENCES EMPLEADO (ID_EMPLEADO)
)

CREATE TABLE SALIDA_PRODUCTO
(
	CANTIDAD INT NOT NULL,
	VALOR MONEY NOT NULL,
	ID_PRODUCTO_FK_SALIDA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_PRODUCTO_FK_SALIDA_PRODUCTO FOREIGN KEY (ID_PRODUCTO_FK_SALIDA_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
	ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO BIGINT NOT NULL,
	CONSTRAINT ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO FOREIGN KEY (ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO) REFERENCES SALIDA_INVENTARIO (ID_SALIDA_INVENTARIO)
)

CREATE TABLE SALIDA_PLANTA
(
	OBSERVACIONES VARCHAR (100) NOT NULL,
	CANTIDAD INT NOT NULL,
	ID_PLANTA_FK_SALIDA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_PLANTA_FK_SALIDA_PLANTA FOREIGN KEY (ID_PLANTA_FK_SALIDA_PLANTA) REFERENCES PLANTA (ID_PLANTA),
	ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA BIGINT NOT NULL,
	CONSTRAINT ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA FOREIGN KEY (ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA) REFERENCES SALIDA_INVENTARIO (ID_SALIDA_INVENTARIO)
)