USE VITAGARDENN_1

SELECT * FROM EMPLEADO

CREATE PROCEDURE CONSULTA_GENERAL_EMPLEADO
AS
SELECT * FROM EMPLEADO

CREATE PROCEDURE CONSULTA_ESPECIFICA_EMPLEADO
@ID_EMPLEADO BIGINT
AS
SELECT NOMBRE
FROM EMPLEADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

CREATE PROCEDURE CONSULTA_ESPECIFICA_EMPLEADO_2
@ID_EMPLEADO BIGINT
AS
SELECT EMAIL
FROM EMPLEADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

CREATE PROCEDURE CONSULTA_ESPECIFICA_EMPLEADO_3
@ID_EMPLEADO BIGINT 
AS
SELECT SALARIO
FROM EMPLEADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

CREATE PROCEDURE CONSULTA_ESPECIFICA_EMPLEADO_4
@ID_EMPLEADO BIGINT 
AS
SELECT ESTADO
FROM EMPLEADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

SELECT * FROM ESPECIE

CREATE PROCEDURE CONSULTA_GENERAL_ESPECIE
AS
SELECT * FROM ESPECIE

CREATE PROCEDURE CONSULTA_ESPECIFICA_ESPECIE
@ID_ESPECIE BIGINT 
AS
SELECT NOMBRE
FROM ESPECIE
WHERE ID_ESPECIE = @ID_ESPECIE

CREATE PROCEDURE CONSULTA_ESPECIFICA_ESPECIE_1
@ID_ESPECIE BIGINT
AS
SELECT ESTADO
FROM ESPECIE
WHERE ID_ESPECIE = @ID_ESPECIE

SELECT * FROM VENTA 

CREATE PROCEDURE CONSULTA_GENERAL_VENTA
AS
SELECT * FROM VENTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA
@ID_VENTA BIGINT 
AS
SELECT VALOR, CANTIDAD
FROM VENTA
WHERE ID_VENTA = @ID_VENTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_2
@ID_VENTA BIGINT 
AS
SELECT VALOR, FECHA, IVA
FROM VENTA
WHERE ID_VENTA = @ID_VENTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_3
@ID_VENTA BIGINT 
AS
SELECT CANTIDAD, VALOR, IVA
FROM VENTA
WHERE ID_VENTA = @ID_VENTA

SELECT * FROM ENTRADA_COMPRA

CREATE PROCEDURE CONSULTA_GENERAL_ENTRADA_COMPRA
AS
SELECT * FROM ENTRADA_COMPRA

CREATE PROCEDURE CONSULTA_ESPECIFICA_ENTRADA_COMPRA
@ID_ENTRADA_COMPRA BIGINT
AS 
SELECT FECHA
FROM ENTRADA_COMPRA
WHERE ID_ENTRADA_COMPRA =  @ID_ENTRADA_COMPRA

CREATE PROCEDURE CONSULTA_ESPECIFICA_ENTRADA_COMPRA_2
@ID_ENTRADA_COMPRA BIGINT 
AS
SELECT ESTADO
FROM ENTRADA_COMPRA
WHERE ID_ENTRADA_COMPRA = @ID_ENTRADA_COMPRA

SELECT * FROM COMPRA

CREATE PROCEDURE CONSULTA_GENERAL_COMPRA
AS
SELECT * FROM COMPRA

CREATE PROCEDURE CONSULTA_ESPECIFICA_COMPRA
@ID_COMPRA BIGINT
AS
SELECT CANTIDAD
FROM COMPRA
WHERE ID_COMPRA = @ID_COMPRA

CREATE PROCEDURE CONSULTA_ESPECIFICA_COMPRA_2
@ID_COMPRA BIGINT
AS
SELECT VALOR
FROM COMPRA
WHERE ID_COMPRA = @ID_COMPRA

CREATE PROCEDURE CONSULTA_ESPECIFICA_COMPRA_3
@ID_COMPRA BIGINT
AS
SELECT ESTADO
FROM COMPRA
WHERE ID_COMPRA = @ID_COMPRA

SELECT * FROM TELEFONO_EMPLEADO

CREATE PROCEDURE CONSULTA_GENERAL_TELEFONO_EMPLEADO
AS
SELECT * FROM TELEFONO_EMPLEADO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO_EMPLEADO
@ID_TELEFONO BIGINT 
AS
SELECT NUMERO 
FROM TELEFONO_EMPLEADO
WHERE ID_TELEFONO = @ID_TELEFONO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO_EMPLEADO_2
@ID_TELEFONO BIGINT 
AS
SELECT ID_EMPLEADO_FK_TELEFONO
FROM TELEFONO_EMPLEADO
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM USUARIO

CREATE PROCEDURE CONSULTA_GENERAL_USUARIO
AS
SELECT * FROM USUARIO

CREATE PROCEDURE CONSULTA_ESPECIFICA_USUARIO
@NOMBRE VARCHAR(40)
AS
SELECT CONTRASEÑA
FROM USUARIO
WHERE NOMBRE = @NOMBRE

CREATE PROCEDURE CONSULTA_ESPECIFICA_USUARIO_2
@NOMBRE VARCHAR(40)
AS
SELECT ID_EMPLEADO_FK_USUARIO
FROM USUARIO
WHERE NOMBRE = @NOMBRE

SELECT * FROM CLIENTE

CREATE PROCEDURE CONSULTA_GENERAL_CLIENTE
AS
SELECT * FROM CLIENTE

CREATE PROCEDURE CONSULTA_ESPECIFICA_CLIENTE
@ID_CLIENTE BIGINT
AS
SELECT EMAIL
FROM CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

CREATE PROCEDURE CONSULTA_ESPECIFICA_CLIENTE_2
@ID_CLIENTE BIGINT
AS
SELECT NOMBRE
FROM CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

CREATE PROCEDURE CONSULTA_ESPECIFICA_CLIENTE_3
@ID_CLIENTE BIGINT
AS
SELECT ID_EMPLEADO_FK_CLIENTE
FROM CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

CREATE PROCEDURE CONSULTA_ESPECIFICA_CLIENTE_4
@ID_CLIENTE BIGINT
AS
SELECT ESTADO
FROM CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

SELECT * FROM TELEFONO_CLIENTE

CREATE PROCEDURE CONSULTA_GENERAL_TELEFONO_CLIENTE
AS
SELECT * FROM TELEFONO_CLIENTE

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO_CLIENTE
@ID_TELEFONO BIGINT 
AS
SELECT NUMERO
FROM TELEFONO_CLIENTE
WHERE ID_TELEFONO = @ID_TELEFONO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO_CLIENTE_2
@ID_TELEFONO BIGINT 
AS
SELECT ID_CLIENTE_FK_TELEFONO
FROM TELEFONO_CLIENTE
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PROVEEDOR

CREATE PROCEDURE CONSULTA_GENERAL_PROVEEDOR
AS
SELECT * FROM PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR
@ID_PROVEEDOR BIGINT 
AS
SELECT NOMBRE
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR_2
@ID_PROVEEDOR BIGINT 
AS
SELECT VALOR
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR_3
@ID_PROVEEDOR BIGINT 
AS
SELECT CIUDAD
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR_4
@ID_PROVEEDOR BIGINT 
AS
SELECT DIRECCION
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR_5
@ID_PROVEEDOR BIGINT 
AS
SELECT ID_EMPLEADO_FK_PROVEEDOR
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_PROVEEDOR_6
@ID_PROVEEDOR BIGINT 
AS
SELECT ESTADO
FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

SELECT * FROM TELEFONO_PROVEEDOR

CREATE PROCEDURE CONSULTA_GENERAL_TELEFONO_PROVEEDOR
AS
SELECT * FROM TELEFONO_PROVEEDOR

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO_PROVEEDOR
@ID_TELEFONO BIGINT 
AS
SELECT NUMERO
FROM TELEFONO_PROVEEDOR
WHERE ID_TELEFONO = @ID_TELEFONO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TELEFONO__PROVEEDOR_2
@ID_TELEFONO BIGINT 
AS
SELECT ID_PROVEEDOR_FK_TELEFONO
FROM TELEFONO_PROVEEDOR
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_PRODUCTO
AS
SELECT * FROM PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO
@ID_PRODUCTO BIGINT
AS
SELECT NOMBRE
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO_2
@ID_PRODUCTO BIGINT
AS
SELECT VALOR
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO_3
@ID_PRODUCTO BIGINT
AS
SELECT CANTIDAD
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO_4
@ID_PRODUCTO BIGINT
AS
SELECT ID_EMPLEADO_FK_PRODUCTO
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO_5
@ID_PRODUCTO BIGINT
AS
SELECT ID_PROVEEDOR_FK_PRODUCTO
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_PRODUCTO_6
@ID_PRODUCTO BIGINT
AS
SELECT ESTADO
FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

SELECT * FROM TIPO_PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_TIPO_PRODUCTO
AS
SELECT * FROM TIPO_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TIPO_PRODUCTO
@ID_TIPO_PRODUCTO BIGINT 
AS
SELECT NOMBRE 
FROM TIPO_PRODUCTO
WHERE ID_TIPO_PRODUCTO = @ID_TIPO_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_TIPO_PRODUCTO_2
@ID_TIPO_PRODUCTO BIGINT 
AS
SELECT ID_PRODUCTO_FK_TIPO_PRODUCTO
FROM TIPO_PRODUCTO
WHERE ID_TIPO_PRODUCTO = @ID_TIPO_PRODUCTO

SELECT * FROM MARCA

CREATE PROCEDURE CONSULTA_GENERAL_MARCA
AS
SELECT * FROM MARCA

CREATE PROCEDURE CONSULTA_ESPECIFICA_MARCA
@ID_MARCA BIGINT
AS 
SELECT NOMBRE
FROM MARCA
WHERE ID_MARCA = @ID_MARCA

CREATE PROCEDURE CONSULTA_ESPECIFICA_MARCA_2
@ID_MARCA BIGINT
AS 
SELECT ID_PRODUCTO_FK_MARCA
FROM MARCA
WHERE ID_MARCA = @ID_MARCA

SELECT * FROM VENTA_PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_VENTA_PRODUCTO
AS
SELECT * FROM VENTA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_PRODUCTO
@ID_PRODCUTO_FK_VENTA_PRODUCTO BIGINT
AS
SELECT OBSERVACIONES
FROM VENTA_PRODUCTO
WHERE ID_PRODUCTO_FK_VENTA_PRODUCTO = @ID_PRODCUTO_FK_VENTA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_PRODUCTO_2
@ID_PRODCUTO_FK_VENTA_PRODUCTO BIGINT
AS
SELECT ID_VENTA_FK_VENTA_PRODUCTO
FROM VENTA_PRODUCTO
WHERE ID_PRODUCTO_FK_VENTA_PRODUCTO = @ID_PRODCUTO_FK_VENTA_PRODUCTO

SELECT * FROM PLANTA

CREATE PROCEDURE CONSULTA_GENERAL_PLANTA
AS
SELECT * FROM PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_PLANTA
@ID_PLANTA BIGINT 
AS
SELECT NOMBRE
FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_PLANTA_2
@ID_PLANTA BIGINT 
AS
SELECT VALOR
FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_PLANTA_3
@ID_PLANTA BIGINT 
AS
SELECT CANTIDAD
FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_PLANTA_4
@ID_PLANTA BIGINT 
AS
SELECT ID_ESPECIE_FK_PLANTA
FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_PLANTA_5
@ID_PLANTA BIGINT 
AS
SELECT ID_EMPLEADO_FK_PLANTA
FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

SELECT * FROM VENTA_PLANTA

CREATE PROCEDURE CONSULTA_GENERAL_VENTA_PLANTA
AS
SELECT * FROM VENTA_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_PLANTA
@ID_PLANTA_FK_VENTA_PLANTA BIGINT
AS 
SELECT OBSERVACIONES
FROM VENTA_PLANTA
WHERE ID_PLANTA_FK_VENTA_PLANTA = @ID_PLANTA_FK_VENTA_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_VENTA_PLANTA_1
@ID_PLANTA_FK_VENTA_PLANTA BIGINT
AS 
SELECT ID_VENTA_FK_VENTA_PLANTA
FROM VENTA_PLANTA
WHERE ID_PLANTA_FK_VENTA_PLANTA = @ID_PLANTA_FK_VENTA_PLANTA

SELECT * FROM ENTRADA_PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_ENTRADA_PRODUCTO
AS
SELECT * FROM ENTRADA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICO_ENTRADA_PRODUCTO
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT
AS
SELECT CANTIDAD
FROM ENTRADA_PRODUCTO
WHERE ID_PRODUCTO_FK_ENTRADA_PRODUCTO = @ID_PRODUCTO_FK_ENTRADA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICO_ENTRADA_PRODUCTO_2
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT
AS
SELECT VALOR
FROM ENTRADA_PRODUCTO
WHERE ID_PRODUCTO_FK_ENTRADA_PRODUCTO = @ID_PRODUCTO_FK_ENTRADA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICO_ENTRADA_PRODUCTO_3
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT
AS
SELECT ID_ENTRADA_COMPRA_FK_VENTA_ENTRADA
FROM ENTRADA_PRODUCTO
WHERE ID_PRODUCTO_FK_ENTRADA_PRODUCTO = @ID_PRODUCTO_FK_ENTRADA_PRODUCTO

SELECT * FROM COMPRA_PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_COMPRA_PRODUCTO
AS
SELECT * FROM COMPRA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_COMPRA_PRODUCTO
@ID_PRODUCTO_FK_COMPRA_PRODUCTO BIGINT
AS
SELECT FECHA
FROM COMPRA_PRODUCTO
WHERE ID_PRODUCTO_FK_COMPRA_PRODUCTO = @ID_PRODUCTO_FK_COMPRA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_COMPRA_PRODUCTO_1
@ID_PRODUCTO_FK_COMPRA_PRODUCTO BIGINT
AS
SELECT HORA
FROM COMPRA_PRODUCTO
WHERE ID_PRODUCTO_FK_COMPRA_PRODUCTO = @ID_PRODUCTO_FK_COMPRA_PRODUCTO

SELECT * FROM ENTRADA_PLANTA

CREATE PROCEDURE CONSULTA_GENERAL_ENTRADA_PLANTA
AS
SELECT * FROM ENTRADA_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_ENTRADA_PLANTA_1
@ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA BIGINT
AS
SELECT OBSERVACIONES
FROM ENTRADA_PLANTA
WHERE ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA = @ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA

SELECT * FROM SALIDA_INVENTARIO

CREATE PROCEDURE CONSULTA_GENERAL_SALIDA_INVENTARIO
AS
SELECT * FROM SALIDA_INVENTARIO

CREATE PROCEDURE CONSULTA_ESPECIFICA_SALIDA_INVENTARIO
@ID_SALIDA_INVENTARIO BIGINT
AS
SELECT FECHA
FROM SALIDA_INVENTARIO
WHERE ID_SALIDA_INVENTARIO = @ID_SALIDA_INVENTARIO

CREATE PROCEDURE CONSULTA_ESPECIFICA_SALIDA_INVENTARIO_1
@ID_SALIDA_INVENTARIO BIGINT
AS
SELECT ESTADO
FROM SALIDA_INVENTARIO
WHERE ID_SALIDA_INVENTARIO = @ID_SALIDA_INVENTARIO

SELECT * FROM SALIDA_PRODUCTO

CREATE PROCEDURE CONSULTA_GENERAL_SALIDA_PRODUCTO
AS
SELECT * FROM SALIDA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_SALIDA_PRODUCTO
@ID_PRODUCTO_FK_SALIDA_PRODUCTO BIGINT
AS
SELECT CANTIDAD
FROM SALIDA_PRODUCTO
WHERE ID_PRODUCTO_FK_SALIDA_PRODUCTO = @ID_PRODUCTO_FK_SALIDA_PRODUCTO

CREATE PROCEDURE CONSULTA_ESPECIFICA_SALIDA_PRODUCTO_1
@ID_PRODUCTO_FK_SALIDA_PRODUCTO BIGINT
AS
SELECT VALOR
FROM SALIDA_PRODUCTO
WHERE ID_PRODUCTO_FK_SALIDA_PRODUCTO = @ID_PRODUCTO_FK_SALIDA_PRODUCTO

SELECT * FROM SALIDA_PLANTA

CREATE PROCEDURE CONSULTA_GENERAL_SALIDA_PLANTA
AS
SELECT * FROM SALIDA_PLANTA

CREATE PROCEDURE CONSULTA_ESPECIFICA_SALIDA_PLANTA
@ID_PLANTA_FK_SALIDA_PLANTA BIGINT
AS
SELECT OBSERVACIONES
FROM SALIDA_PLANTA
WHERE ID_PLANTA_FK_SALIDA_PLANTA = @ID_PLANTA_FK_SALIDA_PLANTA

