USE VITAGARDENN_1

SELECT * FROM EMPLEADO

CREATE PROCEDURE ACTUALIZAR_EMPLEADO
@ID_EMPLEADO BIGINT,
@NOMBRE VARCHAR(30),
@EMAIL VARCHAR(40),
@SALARIO MONEY,
@ESTADO VARCHAR(50)
AS
UPDATE EMPLEADO
SET ID_EMPLEADO = @ID_EMPLEADO, NOMBRE = @NOMBRE, EMAIL = @EMAIL, SALARIO = @SALARIO, ESTADO = @ESTADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

SELECT * FROM ESPECIE

CREATE PROCEDURE ACTUALIZAR_ESPECIE
@ID_ESPECIE BIGINT,
@NOMBRE VARCHAR(40),
@ESTADO VARCHAR(50)
AS
UPDATE ESPECIE
SET ID_ESPECIE = @ID_ESPECIE, NOMBRE = @NOMBRE, ESTADO = @ESTADO
WHERE ID_ESPECIE = @ID_ESPECIE

SELECT * FROM VENTA

CREATE PROCEDURE ACTUALIZAR_VENTA
@ID_VENTA BIGINT,
@VALOR MONEY,
@CANTIDAD INT,
@FECHA DATETIME,
@IVA MONEY,
@ID_EMPLEADO_FK_VENTA BIGINT,
@ID_CLIENTE_FK_VENTA BIGINT
AS
UPDATE VENTA
SET ID_VENTA = @ID_VENTA, VALOR = @VALOR, CANTIDAD = @CANTIDAD, FECHA = @FECHA, IVA = @IVA, ID_EMPLEADO_FK_VENTA = @ID_EMPLEADO_FK_VENTA, ID_CLIENTE_FK_VENTA = @ID_CLIENTE_FK_VENTA
WHERE ID_VENTA = @ID_VENTA

SELECT * FROM ENTRADA_COMPRA

CREATE PROCEDURE ACTUALIZAR_ENTRADA_COMPRA
@ID_ENTRADA_COMPRA BIGINT,
@FECHA DATETIME,
@ESTADO VARCHAR(50),
@ID_COMPRA_FK_ENTRADA_COMPRA BIGINT,
@ID_EMPLEADO_FK_ENTRADA_COMPRA BIGINT
AS
UPDATE ENTRADA_COMPRA
SET ID_ENTRADA_COMPRA = @ID_ENTRADA_COMPRA, FECHA = @FECHA, ESTADO = @ESTADO, ID_COMPRA_FK_ENTRADA_COMPRA = @ID_COMPRA_FK_ENTRADA_COMPRA, ID_EMPLEADO_FK_ENTRADA_COMPRA = @ID_EMPLEADO_FK_ENTRADA_COMPRA
WHERE ID_ENTRADA_COMPRA = @ID_ENTRADA_COMPRA

SELECT * FROM COMPRA

CREATE PROCEDURE ACTUALIZAR_COMPRA
@ID_COMPRA BIGINT,
@CANTIDAD INT,
@VALOR MONEY,
@ESTADO VARCHAR(50),
@ID_EMPLEADO_FK_COMPRA BIGINT,
@ID_PROVEEDOR_FK_COMPRA BIGINT
AS
UPDATE COMPRA
SET ID_COMPRA = @ID_COMPRA, CANTIDAD = @CANTIDAD, VALOR = @VALOR, ESTADO = @ESTADO, ID_EMPLEADO_FK_COMPRA = @ID_EMPLEADO_FK_COMPRA, ID_PROVEEDOR_FK_COMPRA = @ID_PROVEEDOR_FK_COMPRA
WHERE ID_COMPRA = @ID_COMPRA

SELECT * FROM TELEFONO_EMPLEADO

CREATE PROCEDURE ACTUALIZAR_TELEFONO_EMPLEADO
@ID_TELEFONO BIGINT,
@NUMERO INT,
@ID_EMPLEADO_FK_TELEFONO BIGINT
AS
UPDATE TELEFONO_EMPLEADO
SET ID_TELEFONO = @ID_TELEFONO, NUMERO = @NUMERO, ID_EMPLEADO_FK_TELEFONO = @ID_EMPLEADO_FK_TELEFONO
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM USUARIO

CREATE PROCEDURE ACTUALIZAR_USUARIO
@NOMBRE VARCHAR(40),
@CONTRASEÑA INT,
@ID_EMPLEADO_FK_USUARIO BIGINT
AS
UPDATE USUARIO
SET NOMBRE = @NOMBRE, CONTRASEÑA = @CONTRASEÑA, ID_EMPLEADO_FK_USUARIO = @ID_EMPLEADO_FK_USUARIO
WHERE NOMBRE = @NOMBRE

SELECT * FROM CLIENTE

CREATE PROCEDURE ACTUALIZAR_CLIENTE
@ID_CLIENTE BIGINT,
@EMAIL VARCHAR(40),
@NOMBRE VARCHAR(40),
@ESTADO VARCHAR(50),
@ID_EMPLEADO_FK_CLIENTE BIGINT
AS
UPDATE CLIENTE
SET ID_CLIENTE = @ID_CLIENTE, EMAIL = @EMAIL, NOMBRE = @NOMBRE, ESTADO = @ESTADO, ID_EMPLEADO_FK_CLIENTE = @ID_EMPLEADO_FK_CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

SELECT * FROM TELEFONO_CLIENTE

CREATE PROCEDURE ACTUALIZAR_TELEFONO_CLIENTE
@ID_TELEFONO BIGINT,
@NUMERO INT,
@ID_CLIENTE_FK_TELEFONO BIGINT
AS
UPDATE TELEFONO_CLIENTE 
SET ID_TELEFONO = @ID_TELEFONO, NUMERO = @NUMERO, ID_CLIENTE_FK_TELEFONO = @ID_CLIENTE_FK_TELEFONO
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PROVEEDOR

CREATE PROCEDURE ACTUALIZAR_PROVEEDOR
@ID_PROVEEDOR BIGINT,
@NOMBRE VARCHAR(40),
@VALOR MONEY,
@CIUDAD VARCHAR(30),
@DIRECCION VARCHAR(40),
@ESTADO VARCHAR(50),
@ID_EMPLEADO_FK_PROVEEDOR BIGINT
AS
UPDATE PROVEEDOR
SET ID_PROVEEDOR = @ID_PROVEEDOR, NOMBRE = @NOMBRE, VALOR = @VALOR, CIUDAD = @CIUDAD, DIRECCION = @DIRECCION, ESTADO = @ESTADO, ID_EMPLEADO_FK_PROVEEDOR = @ID_EMPLEADO_FK_PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

SELECT * FROM TELEFONO_PROVEEDOR

CREATE PROCEDURE ACTUALIZAR_TELEFONO_PROVEEDOR
@ID_TELEFONO BIGINT,
@NUMERO INT,
@ID_PROVEEDOR_FK_TELEFONO BIGINT
AS
UPDATE TELEFONO_PROVEEDOR
SET ID_TELEFONO = @ID_TELEFONO, NUMERO = @NUMERO, ID_PROVEEDOR_FK_TELEFONO = @ID_PROVEEDOR_FK_TELEFONO
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PRODUCTO

CREATE PROCEDURE ACTUALIZAR_PRODUCTO
@ID_PRODUCTO BIGINT,
@NOMBRE VARCHAR(40),
@VALOR  MONEY,
@CANTIDAD INT,
@ESTADO VARCHAR(50),
@ID_EMPLEADO_FK_PRODUCTO BIGINT,
@ID_PROVEEDOR_FK_PRODUCTO BIGINT
AS
UPDATE PRODUCTO
SET ID_PRODUCTO = @ID_PRODUCTO, NOMBRE = @NOMBRE, VALOR = @VALOR, CANTIDAD = @CANTIDAD, ESTADO = @ESTADO, ID_EMPLEADO_FK_PRODUCTO = @ID_EMPLEADO_FK_PRODUCTO, ID_PROVEEDOR_FK_PRODUCTO = @ID_PROVEEDOR_FK_PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

SELECT * FROM TIPO_PRODUCTO

CREATE PROCEDURE ACTUALIZAR_TIPO_PRODUCTO
@ID_TIPO_PRODUCTO BIGINT,
@NOMBRE VARCHAR(40),
@ESTADO VARCHAR(50),
@ID_PRODUCTO_FK_TIPO_PRODUCTO BIGINT
AS
UPDATE TIPO_PRODUCTO
SET ID_TIPO_PRODUCTO = @ID_TIPO_PRODUCTO, NOMBRE = @NOMBRE, ESTADO = @ESTADO, ID_PRODUCTO_FK_TIPO_PRODUCTO = @ID_PRODUCTO_FK_TIPO_PRODUCTO
WHERE ID_TIPO_PRODUCTO = @ID_TIPO_PRODUCTO

SELECT * FROM MARCA

CREATE PROCEDURE ACTUALIZAR_MARCA
@ID_MARCA BIGINT,
@NOMBRE VARCHAR(30),
@ID_PRODUCTO_FK_MARCA BIGINT
AS
UPDATE MARCA
SET ID_MARCA = @ID_MARCA, NOMBRE = @NOMBRE, ID_PRODUCTO_FK_MARCA = @ID_PRODUCTO_FK_MARCA
WHERE ID_MARCA = @ID_MARCA

SELECT * FROM VENTA_PRODUCTO

CREATE PROCEDURE ACTUALIZAR_VENTA_PRODUCTO
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_VENTA_PRODUCTO BIGINT,
@ID_VENTA_FK_VENTA_PRODUCTO BIGINT
AS
UPDATE VENTA_PRODUCTO
SET OBSERVACIONES = @OBSERVACIONES, CANTIDAD = @CANTIDAD, VALOR = @VALOR, ID_PRODUCTO_FK_VENTA_PRODUCTO = @ID_PRODUCTO_FK_VENTA_PRODUCTO, ID_VENTA_FK_VENTA_PRODUCTO = @ID_VENTA_FK_VENTA_PRODUCTO
WHERE ID_PRODUCTO_FK_VENTA_PRODUCTO = @ID_PRODUCTO_FK_VENTA_PRODUCTO

SELECT * FROM PLANTA

CREATE PROCEDURE ACTUALIZAR_PLANTA
@ID_PLANTA BIGINT,
@NOMRE VARCHAR(60),
@VALOR MONEY,
@CANTIDAD INT,
@ESTADO VARCHAR(50),
@ID_ESPECIE_FK_PLANTA BIGINT,
@ID_EMPLEADO_FK_PLANTA BIGINT
AS
UPDATE PLANTA
SET ID_PLANTA = @ID_PLANTA, NOMBRE = @NOMRE, VALOR = @VALOR, CANTIDAD = @CANTIDAD, ESTADO = @ESTADO, ID_ESPECIE_FK_PLANTA = @ID_ESPECIE_FK_PLANTA, ID_EMPLEADO_FK_PLANTA = @ID_EMPLEADO_FK_PLANTA
WHERE ID_PLANTA = @ID_PLANTA

SELECT * FROM VENTA_PLANTA

CREATE PROCEDURE ACTUALIZAR_VENTA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT,
@SUBTOTAL MONEY,
@ID_PLANTA_FK_VENTA_PLANTA BIGINT,
@ID_VENTA_FK_VENTA_PLANTA BIGINT
AS
UPDATE VENTA_PLANTA
SET OBSERVACIONES = @OBSERVACIONES, CANTIDAD = @CANTIDAD, SUBTOTAL = @SUBTOTAL, ID_PLANTA_FK_VENTA_PLANTA = @ID_PLANTA_FK_VENTA_PLANTA, ID_VENTA_FK_VENTA_PLANTA = @ID_VENTA_FK_VENTA_PLANTA
WHERE ID_PLANTA_FK_VENTA_PLANTA = @ID_PLANTA_FK_VENTA_PLANTA

SELECT * FROM ENTRADA_PRODUCTO

CREATE PROCEDURE ACTUALIZAR_ENTRADA_PRODUCTO
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT,
@ID_ENTRADA_PRODUCTO_FK_VENTA_ENTRADA BIGINT
AS
UPDATE ENTRADA_PRODUCTO
SET CANTIDAD = @CANTIDAD, VALOR = @VALOR, ID_PRODUCTO_FK_ENTRADA_PRODUCTO = @ID_PRODUCTO_FK_ENTRADA_PRODUCTO, ID_ENTRADA_COMPRA_FK_VENTA_ENTRADA = @ID_ENTRADA_PRODUCTO_FK_VENTA_ENTRADA
WHERE CANTIDAD = @CANTIDAD

SELECT * FROM COMPRA_PRODUCTO

CREATE PROCEDURE ACTUALIZAR_COMPRA_PRODUCTO
@FECHA DATETIME,
@HORA DATETIME,
@ID_PRODUCTO_FK_COMPRA_PRODUCTO BIGINT,
@ID_COMPRA_FK_COMPRA_PRODUCTO BIGINT
AS
UPDATE COMPRA_PRODUCTO
SET FECHA = @FECHA, HORA = @HORA, ID_PRODUCTO_FK_COMPRA_PRODUCTO = @ID_PRODUCTO_FK_COMPRA_PRODUCTO, ID_COMPRA_FK_COMPRA_PRODUCTO = @ID_COMPRA_FK_COMPRA_PRODUCTO
WHERE FECHA = @FECHA

SELECT * FROM ENTRADA_PLANTA 

CREATE PROCEDURE ACTUALIZAR_ENTRADA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT,
@ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA BIGINT,
@ID_PLANTA_FK_ENTRADA_PLANTA BIGINT
AS
UPDATE ENTRADA_PLANTA
SET OBSERVACIONES = @OBSERVACIONES, CANTIDAD = @CANTIDAD, ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA = @ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA, ID_PLANTA_FK_ENTRADA_PLANTA = @ID_PLANTA_FK_ENTRADA_PLANTA
WHERE ID_PLANTA_FK_ENTRADA_PLANTA = @ID_PLANTA_FK_ENTRADA_PLANTA

SELECT * FROM SALIDA_INVENTARIO

CREATE PROCEDURE ACTUALIZAR_SALIDA_INVENTARIO
@ID_SALIDA_INVENTARIO BIGINT,
@FECHA DATETIME,
@ESTADO VARCHAR(50),
@ID_VENTA_FK_SALIDA_INVENTARIO BIGINT,
@ID_EMPLEADO_FK_SALIDA_INVENTARIO BIGINT
AS
UPDATE SALIDA_INVENTARIO
SET ID_SALIDA_INVENTARIO = @ID_SALIDA_INVENTARIO, FECHA = @FECHA, ESTADO = @ESTADO, ID_VENTA_FK_SALIDA_INVENTARIO = @ID_VENTA_FK_SALIDA_INVENTARIO, ID_EMPLEADO_FK_SALIDA_INVENTARIO = @ID_EMPLEADO_FK_SALIDA_INVENTARIO
WHERE ID_SALIDA_INVENTARIO = @ID_SALIDA_INVENTARIO

SELECT * FROM SALIDA_PRODUCTO

CREATE PROCEDURE ACTUALIZAR_SALIDA_PRODUCTO
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_SALIDA_PRODUCTO BIGINT,
@ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO BIGINT
AS
UPDATE SALIDA_PRODUCTO 
SET CANTIDAD = @CANTIDAD, VALOR = @VALOR, ID_PRODUCTO_FK_SALIDA_PRODUCTO = @ID_PRODUCTO_FK_SALIDA_PRODUCTO, ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO = @ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO
WHERE CANTIDAD = @CANTIDAD

SELECT * FROM SALIDA_PLANTA

CREATE PROCEDURE ACTUALIZAR_SALIDA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT, 
@ID_PLANTA_FK_SALIDA_PLANTA BIGINT,
@ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA BIGINT
AS
UPDATE SALIDA_PLANTA
SET OBSERVACIONES = @OBSERVACIONES, CANTIDAD = @CANTIDAD, ID_PLANTA_FK_SALIDA_PLANTA = @ID_PLANTA_FK_SALIDA_PLANTA, ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA = @ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA
WHERE ID_PLANTA_FK_SALIDA_PLANTA = @ID_PLANTA_FK_SALIDA_PLANTA