USE VITAGARDENN_1

SELECT * FROM EMPLEADO

CREATE PROCEDURE ELIMINAR_EMPLEADO
@ID_EMPLEADO BIGINT
AS
DELETE FROM EMPLEADO
WHERE ID_EMPLEADO = @ID_EMPLEADO

SELECT * FROM ESPECIE

CREATE PROCEDURE ELIMINAR_ESPECIE
@ID_ESPECIE BIGINT
AS
DELETE FROM ESPECIE
WHERE ID_ESPECIE = @ID_ESPECIE

SELECT * FROM VENTA

CREATE PROCEDURE ELIMINAR_VENTA
@ID_VENTA BIGINT
AS
DELETE FROM VENTA
WHERE ID_VENTA = @ID_VENTA

SELECT * FROM ENTRADA_COMPRA

CREATE PROCEDURE ELIMINAR_ENTRADA_COMPRA
@ID_ENTRADA_COMPRA BIGINT
AS
DELETE FROM ENTRADA_COMPRA
WHERE ID_ENTRADA_COMPRA = @ID_ENTRADA_COMPRA

SELECT * FROM COMPRA

CREATE PROCEDURE ELIMINAR_COMPRA
@ID_COMPRA BIGINT
AS
DELETE FROM COMPRA
WHERE ID_COMPRA = @ID_COMPRA

SELECT * FROM TELEFONO_EMPLEADO

CREATE PROCEDURE ELIMINAR_TELEFONO_EMPLEADO
@ID_TELEFONO BIGINT
AS
DELETE FROM TELEFONO_EMPLEADO
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM USUARIO

CREATE PROCEDURE ELIMINAR_USUARIO
@NOMBRE VARCHAR(40)
AS
DELETE FROM USUARIO
WHERE NOMBRE = @NOMBRE

SELECT * FROM CLIENTE

CREATE PROCEDURE ELIMINAR_CLIENTE
@ID_CLIENTE BIGINT
AS
DELETE FROM CLIENTE
WHERE ID_CLIENTE = @ID_CLIENTE

SELECT * FROM TELEFONO_CLIENTE

CREATE PROCEDURE ELIMINAR_TELEFONO_CLIENTE
@ID_TELEFONO BIGINT
AS
DELETE FROM TELEFONO_CLIENTE
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PROVEEDOR

CREATE PROCEDURE ELIMINAR_PROVEEDOR
@ID_PROVEEDOR BIGINT
AS
DELETE FROM PROVEEDOR
WHERE ID_PROVEEDOR = @ID_PROVEEDOR

SELECT * FROM TELEFONO_PROVEEDOR

CREATE PROCEDURE ELIMINAR_TELEFONO_PROVEEDOR
@ID_TELEFONO BIGINT
AS
DELETE FROM TELEFONO_PROVEEDOR
WHERE ID_TELEFONO = @ID_TELEFONO

SELECT * FROM PRODUCTO

CREATE PROCEDURE ELIMINAR_PRODUCTO
@ID_PRODUCTO BIGINT
AS
DELETE FROM PRODUCTO
WHERE ID_PRODUCTO = @ID_PRODUCTO

SELECT * FROM TIPO_PRODUCTO

CREATE PROCEDURE ELIMINAR_TIPO_PRODUCTO
@ID_TIPO_PRODUCTO BIGINT
AS
DELETE FROM TIPO_PRODUCTO
WHERE ID_TIPO_PRODUCTO = @ID_TIPO_PRODUCTO

SELECT * FROM MARCA

CREATE PROCEDURE ELIMINAR_MARCA
@ID_MARCA BIGINT 
AS
DELETE FROM MARCA
WHERE ID_MARCA = @ID_MARCA

SELECT * FROM VENTA_PRODUCTO

CREATE PROCEDURE ELIMINAR_VENTA_PRODUCTO
@ID_PRODUCTO_FK_VENTA_PRODUCTO BIGINT
AS
DELETE FROM VENTA_PRODUCTO
WHERE ID_PRODUCTO_FK_VENTA_PRODUCTO = @ID_PRODUCTO_FK_VENTA_PRODUCTO

SELECT * FROM PLANTA

CREATE PROCEDURE ELIMINAR_PLANTA
@ID_PLANTA BIGINT
AS
DELETE FROM PLANTA
WHERE ID_PLANTA = @ID_PLANTA

SELECT * FROM VENTA_PLANTA

CREATE PROCEDURE ELIMINAR_VENTA_PLANTA
@ID_PLANTA_FK_VENTA_PLANTA BIGINT
AS
DELETE FROM VENTA_PLANTA
WHERE ID_PLANTA_FK_VENTA_PLANTA = @ID_PLANTA_FK_VENTA_PLANTA

SELECT * FROM ENTRADA_PRODUCTO

CREATE PROCEDURE ELIMINAR_ENTRADA_PRODUCTO
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT
AS
DELETE FROM ENTRADA_PRODUCTO
WHERE ID_PRODUCTO_FK_ENTRADA_PRODUCTO = @ID_PRODUCTO_FK_ENTRADA_PRODUCTO

SELECT * FROM COMPRA_PRODUCTO

CREATE PROCEDURE ELIMINAR_COMPRA_PRODUCTO
@FECHA DATETIME
AS
DELETE FROM COMPRA_PRODUCTO
WHERE FECHA = @FECHA

SELECT * FROM ENTRADA_PLANTA

CREATE PROCEDURE ELIMINAR_ENTRADA_PLANTA
@ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA BIGINT
AS
DELETE FROM ENTRADA_PLANTA
WHERE ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA = @ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA

SELECT * FROM SALIDA_INVENTARIO

CREATE PROCEDURE ELIMINAR_SALIDA_INVENTARIO
@ID_SALIDA_INVANTARIO BIGINT
AS
DELETE FROM SALIDA_INVENTARIO
WHERE ID_SALIDA_INVENTARIO = @ID_SALIDA_INVANTARIO

SELECT * FROM SALIDA_PRODUCTO

CREATE PROCEDURE ELIMINAR_SALIDA_PRODUCTO
@CANTIDAD INT
AS
DELETE FROM SALIDA_PRODUCTO
WHERE CANTIDAD = @CANTIDAD

SELECT * FROM SALIDA_PLANTA

CREATE PROCEDURE ELIMINAR_SALIDA_PLANTA
@ID_PLANTA_FK_SALIDA_PLANTA BIGINT
AS
DELETE FROM SALIDA_PLANTA
WHERE ID_PLANTA_FK_SALIDA_PLANTA = @ID_PLANTA_FK_SALIDA_PLANTA