USE VITAGARDENN_1

SELECT * FROM EMPLEADO

CREATE PROCEDURE INSERTAR_EMPLEADO
@ID_EMPLEADO BIGINT,
@NOMBRE VARCHAR(40),
@EMAIL VARCHAR(40),
@SALARIO MONEY,
@ESTADO VARCHAR(50)
AS
INSERT INTO EMPLEADO (ID_EMPLEADO, NOMBRE, EMAIL, SALARIO, ESTADO)
VALUES (@ID_EMPLEADO,@NOMBRE,@EMAIL,@SALARIO,@ESTADO) 

SELECT * FROM ESPECIE

CREATE PROCEDURE INSERTAR_ESPECIE
@ID_ESPECIE BIGINT,
@NOMBRE VARCHAR(40),
@ESTADO VARCHAR(50)
AS
INSERT INTO ESPECIE (ID_ESPECIE, NOMBRE, ESTADO)
VALUES (@ID_ESPECIE,@NOMBRE,@ESTADO)

SELECT * FROM VENTA

CREATE PROCEDURE INSERTAR_VENTA
@ID_VENTA BIGINT,
@VALOR MONEY,
@CANTIDAD INT,
@FECHA DATETIME,
@IVA MONEY,
@ID_EMPLEADO_FK_VENTA BIGINT,
@ID_CLIENTE_FK_VENTA BIGINT 
AS
INSERT INTO VENTA (ID_VENTA, VALOR, CANTIDAD, FECHA, IVA, ID_EMPLEADO_FK_VENTA, ID_CLIENTE_FK_VENTA)
VALUES (@ID_VENTA, @VALOR,@CANTIDAD,@FECHA,@IVA,@ID_EMPLEADO_FK_VENTA, @ID_CLIENTE_FK_VENTA)

SELECT * FROM ENTRADA_COMPRA

CREATE PROCEDURE INSERTAR_ENTRADA_COMPRA
@ID_ENTRADA_COMPRA BIGINT,
@FECHA DATETIME,
@ESTADO VARCHAR(50),
@ID_COMPRA_FK_ENTRADA_COMPRA BIGINT,
@ID_EMPLEADO_FK_ENTRADA_COMPRA BIGINT
AS
INSERT INTO ENTRADA_COMPRA (ID_ENTRADA_COMPRA, FECHA, ESTADO, ID_COMPRA_FK_ENTRADA_COMPRA, ID_EMPLEADO_FK_ENTRADA_COMPRA)
VALUES (@ID_ENTRADA_COMPRA, @FECHA, @ESTADO, @ID_COMPRA_FK_ENTRADA_COMPRA, @ID_EMPLEADO_FK_ENTRADA_COMPRA)

SELECT * FROM COMPRA

CREATE PROCEDURE INSERTAR_COMPRA
@ID_COMPRA BIGINT,
@CANTIDAD INT,
@VALOR MONEY,
@ESTADO VARCHAR (50),
@ID_EMPLEADO_FK_COMPRA BIGINT,
@ID_PROVEEDOR_FK_COMPRA BIGINT 
AS
INSERT INTO COMPRA (ID_COMPRA, CANTIDAD, VALOR, ESTADO, ID_EMPLEADO_FK_COMPRA, ID_PROVEEDOR_FK_COMPRA)
VALUES (@ID_COMPRA, @CANTIDAD,@VALOR, @ESTADO, @ID_EMPLEADO_FK_COMPRA, @ID_PROVEEDOR_FK_COMPRA)

SELECT * FROM TELEFONO_EMPLEADO

CREATE PROCEDURE INSERTAR_TELEFONO_EMPLEADO
@ID_TELEFONO BIGINT,
@NUMERO INT,
@ID_EMPLEADO_FK_TELEFONO BIGINT
AS
INSERT INTO TELEFONO_EMPLEADO (ID_TELEFONO, NUMERO, ID_EMPLEADO_FK_TELEFONO)
VALUES (@ID_TELEFONO, @NUMERO, @ID_EMPLEADO_FK_TELEFONO)

SELECT * FROM USUARIO

CREATE PROCEDURE INSERTAR_USUARIO
@NOMBRE VARCHAR(40),
@CONTRASEÑA INT,
@ID_EMPLEADO_FK_USUARIO BIGINT
AS 
INSERT INTO USUARIO (NOMBRE, CONTRASEÑA, ID_EMPLEADO_FK_USUARIO)
VALUES (@NOMBRE, @CONTRASEÑA, @ID_EMPLEADO_FK_USUARIO)

SELECT * FROM CLIENTE

CREATE PROCEDURE INSERTAR_CLIENTE
@ID_CLIENTE BIGINT,
@EMAIL VARCHAR(40),
@NOMBRE VARCHAR(40),
@ESTADO VARCHAR (50),
@ID_EMPLEADO_FK_CLIENTE BIGINT
AS
INSERT INTO CLIENTE (ID_CLIENTE, EMAIL, NOMBRE, ESTADO, ID_EMPLEADO_FK_CLIENTE)
VALUES (@ID_CLIENTE, @EMAIL, @NOMBRE, @ESTADO, @ID_EMPLEADO_FK_CLIENTE)

SELECT * FROM TELEFONO_CLIENTE

CREATE PROCEDURE INSERTAR_TELEFONO_CLIENTE
@ID_TELEFONO BIGINT,
@NUMERO INT, 
@ID_CLIENTE_FK_TELEFONO BIGINT 
AS
INSERT INTO TELEFONO_CLIENTE (ID_TELEFONO, NUMERO, ID_CLIENTE_FK_TELEFONO)
VALUES (@ID_TELEFONO, @NUMERO, @ID_CLIENTE_FK_TELEFONO)

SELECT * FROM PROVEEDOR

CREATE PROCEDURE INSERTAR_PROVEEDOR
@ID_PROVEEDOR BIGINT,
@NOMBRE VARCHAR(40),
@VALOR MONEY,
@CIUDAD VARCHAR(30),
@DIRECCION VARCHAR(50),
@ESTADO VARCHAR(50),
@ID_EMPLEADO_FK_PROVEEDOR BIGINT
AS
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, VALOR, CIUDAD, DIRECCION, ESTADO, ID_EMPLEADO_FK_PROVEEDOR)
VALUES (@ID_PROVEEDOR, @NOMBRE, @VALOR, @CIUDAD, @DIRECCION, @ESTADO, @ID_EMPLEADO_FK_PROVEEDOR)

SELECT * FROM TELEFONO_PROVEEDOR

CREATE PROCEDURE INSERTAR_TELEFONO_PROVEEDOR
@ID_TELEFONO BIGINT,
@NUMERO INT,
@ID_PROVEEDOR_FK_TELEFONO BIGINT 
AS
INSERT INTO TELEFONO_PROVEEDOR (ID_TELEFONO, NUMERO, ID_PROVEEDOR_FK_TELEFONO)
VALUES (@ID_TELEFONO, @NUMERO, @ID_PROVEEDOR_FK_TELEFONO)

SELECT * FROM PRODUCTO

CREATE PROCEDURE INSERTAR_PRODUCTO
@ID_PRODUCTO BIGINT,
@NOMBRE VARCHAR(30),
@VALOR MONEY,
@CANTIDAD INT,
@ESTADO VARCHAR(50), 
@ID_EMPLEADO_FK_PRODUCTO BIGINT,
@ID_PROVEEDOR_FK_PRODUCTO BIGINT 
AS
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, VALOR, CANTIDAD, ESTADO, ID_EMPLEADO_FK_PRODUCTO, ID_PROVEEDOR_FK_PRODUCTO)
VALUES (@ID_PRODUCTO, @NOMBRE, @VALOR, @CANTIDAD, @ESTADO, @ID_EMPLEADO_FK_PRODUCTO, @ID_PROVEEDOR_FK_PRODUCTO)

SELECT * FROM TIPO_PRODUCTO

CREATE PROCEDURE INSERTAR_TIPO_PRODUCTO
@ID_TIPO_PRODUCTO BIGINT,
@NOMBRE VARCHAR(30),
@ESTADO VARCHAR(50),
@ID_PRODUCTO_FK_TIPO_PRODUCTO BIGINT
AS
INSERT INTO TIPO_PRODUCTO (ID_TIPO_PRODUCTO,NOMBRE,ESTADO,ID_PRODUCTO_FK_TIPO_PRODUCTO)
VALUES (@ID_TIPO_PRODUCTO, @NOMBRE, @ESTADO, @ID_PRODUCTO_FK_TIPO_PRODUCTO)

SELECT * FROM MARCA

CREATE PROCEDURE INSERTAR_MARCA
@ID_MARCA BIGINT,
@NOMBRE VARCHAR(30),
@ID_PRODUCTO_FK_MARCA BIGINT 
AS
INSERT INTO MARCA (ID_MARCA, NOMBRE, ID_PRODUCTO_FK_MARCA)
VALUES (@ID_MARCA, @NOMBRE, @ID_PRODUCTO_FK_MARCA)

SELECT * FROM VENTA_PRODUCTO

CREATE PROCEDURE INSERTAR_VENTA_PRODUCTO
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_VENTA_PRODUCTO BIGINT,
@ID_VENTA_FK_VENTA_PRODUCTO BIGINT
AS
INSERT INTO VENTA_PRODUCTO (OBSERVACIONES,CANTIDAD, VALOR, ID_PRODUCTO_FK_VENTA_PRODUCTO, ID_VENTA_FK_VENTA_PRODUCTO)
VALUES (@OBSERVACIONES,@CANTIDAD, @VALOR, @ID_PRODUCTO_FK_VENTA_PRODUCTO, @ID_VENTA_FK_VENTA_PRODUCTO)

SELECT * FROM PLANTA 

CREATE PROCEDURE INSERTAR_PLANTA
@ID_PLANTA BIGINT,
@NOMBRE VARCHAR(60),
@VALOR MONEY,
@CANTIDAD INT,
@ESTADO VARCHAR(50),
@ID_ESPECIE_FK_PLANTA BIGINT,
@ID_EMPLEADO_FK_PLANTA BIGINT
AS
INSERT INTO PLANTA (ID_PLANTA, NOMBRE, VALOR, CANTIDAD, ESTADO, ID_ESPECIE_FK_PLANTA, ID_EMPLEADO_FK_PLANTA)
VALUES (@ID_PLANTA, @NOMBRE, @VALOR, @CANTIDAD, @ESTADO, @ID_ESPECIE_FK_PLANTA, @ID_EMPLEADO_FK_PLANTA)

SELECT * FROM VENTA_PLANTA

CREATE PROCEDURE INSERTAR_VENTA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT, 
@SUBTOTAL MONEY,
@ID_PLANTA_FK_VENTA_PLANTA BIGINT,
@ID_VENTA_FK_VENTA_PLANTA BIGINT
AS
INSERT INTO VENTA_PLANTA (OBSERVACIONES,CANTIDAD, SUBTOTAL, ID_PLANTA_FK_VENTA_PLANTA, ID_VENTA_FK_VENTA_PLANTA)
VALUES (@OBSERVACIONES,@CANTIDAD, @SUBTOTAL, @ID_PLANTA_FK_VENTA_PLANTA, @ID_VENTA_FK_VENTA_PLANTA)

SELECT * FROM ENTRADA_PRODUCTO

CREATE PROCEDURE INSERTAR_ENTRADA_PRODUCTO
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_ENTRADA_PRODUCTO BIGINT,
@ID_ENTRADA_COMPRA_FK_ENTRADA_PRODUCTO BIGINT
AS
INSERT INTO ENTRADA_PRODUCTO (CANTIDAD, VALOR, ID_PRODUCTO_FK_ENTRADA_PRODUCTO, ID_ENTRADA_COMPRA_FK_VENTA_ENTRADA)
VALUES (@CANTIDAD, @VALOR, @ID_PRODUCTO_FK_ENTRADA_PRODUCTO, @ID_ENTRADA_COMPRA_FK_ENTRADA_PRODUCTO)

SELECT * FROM COMPRA_PRODUCTO

CREATE PROCEDURE INSERTAR_COMPRA_PRODUCTO
@FECHA DATETIME,
@HORA TIME,
@ID_PRODUCTO_FK_COMPRA_PRODUCTO BIGINT,
@ID_COMPRA_FK_COMPRA_PRODUCTO BIGINT
AS
INSERT INTO COMPRA_PRODUCTO (FECHA, HORA, ID_PRODUCTO_FK_COMPRA_PRODUCTO, ID_COMPRA_FK_COMPRA_PRODUCTO)
VALUES (@FECHA, @HORA, @ID_PRODUCTO_FK_COMPRA_PRODUCTO, @ID_COMPRA_FK_COMPRA_PRODUCTO)

SELECT * FROM ENTRADA_PLANTA

CREATE PROCEDURE INSERTAR_ENTRADA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT, 
@ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA BIGINT,
@ID_PLANTA_FK_ENTRADA_PLANTA BIGINT
AS
INSERT INTO ENTRADA_PLANTA (OBSERVACIONES, CANTIDAD, ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA, ID_PLANTA_FK_ENTRADA_PLANTA)
VALUES (@OBSERVACIONES, @CANTIDAD, @ID_ENTRADA_COMPRA_FK_ENTRADA_PLANTA, @ID_PLANTA_FK_ENTRADA_PLANTA)

SELECT * FROM SALIDA_INVENTARIO

CREATE PROCEDURE INSERTAR_SALIDA_INVENTARIO
@ID_SALIDA_INVENTARIO BIGINT,
@FECHA DATETIME,
@ESTADO VARCHAR(50),
@ID_VENTA_FK_SALIDA_INVENTARIO BIGINT,
@ID_EMPLEADO_FK_SALIDA_INVENTARIO BIGINT
AS
INSERT INTO SALIDA_INVENTARIO (ID_SALIDA_INVENTARIO, FECHA, ESTADO, ID_VENTA_FK_SALIDA_INVENTARIO)
VALUES (@ID_SALIDA_INVENTARIO, @FECHA, @ESTADO, @ID_VENTA_FK_SALIDA_INVENTARIO)

SELECT * FROM SALIDA_PRODUCTO

CREATE PROCEDURE INSERTAR_SALIDA_PRODUCTO
@CANTIDAD INT,
@VALOR MONEY,
@ID_PRODUCTO_FK_SALIDA_PRODUCTO BIGINT,
@ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO BIGINT
AS
INSERT INTO SALIDA_PRODUCTO (CANTIDAD, VALOR, ID_PRODUCTO_FK_SALIDA_PRODUCTO, ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO)
VALUES (@CANTIDAD, @VALOR, @ID_PRODUCTO_FK_SALIDA_PRODUCTO, @ID_SALIDA_INVENTARIO_FK_SALIDA_PRODUCTO)

SELECT * FROM SALIDA_PLANTA

CREATE PROCEDURE INSERTAR_SALIDA_PLANTA
@OBSERVACIONES VARCHAR(100),
@CANTIDAD INT, 
@ID_PLANTA_FK_SALIDA_PLANTA BIGINT,
@ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA BIGINT
AS
INSERT INTO SALIDA_PLANTA (OBSERVACIONES, CANTIDAD, ID_PLANTA_FK_SALIDA_PLANTA, ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA)
VALUES (@OBSERVACIONES, @CANTIDAD, @ID_PLANTA_FK_SALIDA_PLANTA, @ID_SALIDA_INVENTARIO_FK_SALIDA_PLANTA)